package com.example.kramelix.feature.chat.model;

/**
 * This enum enumerates the possible speaker roles within a conversation.
 *
 * <p>Each {@link Message} is tagged with a {@code Role} to identify its origin —
 * whether it was authored by the local user or generated by the AI assistant (LLM).
 * This distinction contributes to the visual alignment of chat bubbles and the logic
 * used by higher-level controllers such as
 * {@link com.example.kramelix.feature.chat.controller.ChatController}.</p>
 *
 * <br>
 * <strong>Responsibilities</strong>
 * <ul>
 *     <li>Defines the two valid chat participants: {@link #USER} and {@link #ASSISTANT}.</li>
 *     <li>Serves as a stable enum used throughout message rendering, LLM request building,
 *     and repository updates.</li>
 * </ul>
 *
 * @author Amy Huang
 * @since 1.0
 */
public enum Role {

    /**
     * Messages authored by the end user.
     */
    USER,

    /**
     * Messages generated by the assistant (LLM).
     */
    ASSISTANT

}
